### ISSUE TITLE
ACDisplay clock is wrong

### ISSUE THREAD

**Issue by elieobeid7** [AChep/AcDisplay#100]
ACDisplay clock is wrong sometimes, especially when the phone is locked for a long time, say you're sleeping, for instance I woke up this morning and I saw this

http://i.imgur.com/GEBdAaz.jpghttp://i.imgur.com/GEBdAaz.jpg

while the phone clock is the correct one

http://i.imgur.com/NT3rrKz.jpg

So the time displayed on ACdisplay is 20 minutes earlier than the real time. This issue doesn't always happen but happens nonetheless, especially when the phone is locked for a long time as I said

**Comment by AChep** [comment]
As far as I can see, AcDisplay shows the _right_ time -- 8:06. What are you talking about is the time of notification's arrival -- _7:39 AM_.

**Comment by elieobeid7** [comment]
ok sorry :) and a feature suggestion please, ability to add more than 1 widget on the lock screen
