### ISSUE TITLE
AcDisplay partially breaks trust agents

### ISSUE THREAD

**Issue by equescalculi** [AChep/AcDisplay#105]
Android lets you bypass the lock screen by using trust agents starting with version 5.0. AcDisplay partially breaks this feature. Steps to reproduce:

1. Enable a trust agent and make sure it's active.
2. Put the device in sleep mode.
3. Receive and miss a notification with AcDisplay enabled.
4. Wake the device. The device now needs to be unlocked despite an active trust agent.

**Comment by AChep** [comment]
This bug is not on our side.
