### ISSUE TITLE
Notification access keeps disabling itself

### ISSUE THREAD

**Issue by DenizUgur** [AChep/AcDisplay#108]
I'm running 5.0.1 on gt-i9500

**Comment by DenizUgur** [comment]
issue continuing

**Comment by Digitaldoraemon** [comment]
Update the android version or use custom ROMs. Check the apps you installed. Root access may be a problem. Most likely its just a bug in your phone. Updating your phone to the latest android version may fix it.

**Comment by notom** [comment]
Confirming, there is a problem with android 5.0.1 on gt-i9500.

**Comment by CarlosACepeda** [comment]
Which version of AcDisplay are you running?
Anyhow, I'm closing the issue as stale, if you think it still applies feel free to comment.
