### ISSUE TITLE
Some French labels not displayed

### ISSUE THREAD

**Issue by fredericbeaudoin** [AChep/AcDisplay#109]
Although all strings seem OK on Crowdin, the following are displayed in English on the French UI:
* Settings > Lockscreen: "Lock delay" and "No delay" labels
* Settings > Notifications: "Quick glance" label and "Wake up [...]" description
* Settings > More: "Media widget" label and "Show a media widget [...]" description

Am using Android 4.4.2 on Samsung S4 Mini (model number SGH-I257M).

**Comment by AChep** [comment]
Those strings were untranslated at the moment of build of last version [ https://github.com/AChep/AcDisplay/tree/master/project/app/src/releaseFlavor/res/values-fr ]. They will be included in next build.
