### ISSUE TITLE
notification twitter and other social network

### ISSUE THREAD

**Issue by nidele** [AChep/AcDisplay#110]
hi,
it is possible to aggregate the twitter notification as gmail and other?
i note that for every tweet compare a icon. i should like an icon with the number of notification
best regards

**Comment by CarlosACepeda** [comment]
Please explain better your requirement

**Comment by tjsuominen** [comment]
I think that @nidele means if there are x amount of notifications from the same source (eg. Twitter), those notifications are combined into "one" with a number (superscript?) indicating the count? I guess that kind of ui-behaviour is not supported by Android in general...

**Comment by CarlosACepeda** [comment]
Its currently supported then, a notification count
