### ISSUE TITLE
Screen stays on after connecting/disconnecting charger

### ISSUE THREAD

**Issue by matskb** [AChep/AcDisplay#113]
When I connect or disconnect my charger, the screen turns on (which is fine) but then continues to stay on forever until I manually lock the phone.

The issue occurs on both the OnePlus 2 and the OnePlus X, both running OxygenOS 2.1.1/2.1.2 (Android 5.1.1).
Any suggestions on how to fix this are welcome!

**Comment by Digitaldoraemon** [comment]
Its the setting.. Timeout or sleep setting which should be located in the display settings in your system setting. Don't set it to never but 30 sec or 1 minute is great.

**Comment by CarlosACepeda** [comment]
@matskb  Does this issue still happen? Did you set the timeout time in the settings as suggested by @Digitaldoraemon ?

**Comment by CarlosACepeda** [comment]
Closed as stale, if you think it still happens feel free to comment in order to reopen the issue.
