### ISSUE TITLE
the TOP Activity problerm

### ISSUE THREAD

**Issue by sirius-meng** [AChep/AcDisplay#115]
Sorry, maybe it's a question not a bug.

some music player has the lock screen, but  shown in 3 or 5 sec later, it will cover the AcDisplay.

is there some way to make the activity Top always

**Comment by Digitaldoraemon** [comment]
If you are running KitKat or lower, install xposed. It can be downloaded online. Acdisplay has a exposed module in it. It should help to overlap it but not removing the music player lockscreen. Or you can just disable the music player lockscreen which should be in the music play settings.

**Comment by CarlosACepeda** [comment]
closing as stale.
