### ISSUE TITLE
MX player

### ISSUE THREAD

**Issue by llcool** [AChep/AcDisplay#121]
Media player controls are not displayed on AcDisplay (v3.8.4) screen but are display on the Android notification panel.

Samsung Note 3 Android 5.0

**Comment by CarlosACepeda** [comment]
The controls being displayed on the Lockscreen are not controlled by the app itself but by an Android API that notifies listener about changes in the media. in the case of Lollipop that would be the [MediaSessionsManager](https://developer.android.com/reference/android/media/session/MediaSessionManager)
ahm, if the MusicPlayer does not register a MediaSession to play it's media then the MediaSessionsManager can't notify listeners about this MediaSession, thus, app not being able to show controls on the screen.

**Comment by CarlosACepeda** [comment]
Im closing the issue, if you think it still happens, please attach logs, screenshots and any other useful information.
