### ISSUE TITLE
Notifications broken after 6.0.1 upgrade

### ISSUE THREAD

**Issue by kaschm** [AChep/AcDisplay#128]
Thanks for a great app! 

I'm on a Samsung edge 6 and just upgraded to Android 6.0.1. The lock screen still looks and functions (unlocks) the same, but notification icons are no longer showing up.

**Comment by AChep** [comment]
Thanks, I'll fix this ASAP.

**Comment by jius94** [comment]
same problem wirh my oppo r9s

**Comment by CarlosACepeda** [comment]
Closing as stale, if you think it is still applies, then write and I'll reopen the issue.
