### ISSUE TITLE
Unpossible to uninstall AcDisplay.

### ISSUE THREAD

**Issue by Shockwave0227** [AChep/AcDisplay#129]
Hello! I want to uninstall AcDisplay. I know that first of all I need to diable it from system administrator list, but every time I try to do it, small error appear and unchecking menu crashes with info "com.android.settings" stoped.  Also, several weeks ago i updated to Android Marshamellow version, maybe it may be important

**Comment by AChep** [comment]
Do you have custom ROM installed? You can try to uninstall by opening AcDisplay / Help and clicking on "uninstall" link.
![zplo1clmnxw](https://cloud.githubusercontent.com/assets/990982/14949919/8f9b090a-1056-11e6-9f62-c1ea5e96a8b4.jpg)

**Comment by Shockwave0227** [comment]
Hi!
No I hame standart ROM, no manual changes. Now I`am little bit away from my phone, but I will try as soon as possible, and will reply about my progress

**Comment by AChep** [comment]
@Shockwave0227 did it help?

**Comment by CarlosACepeda** [comment]
Closing as stale.
