### ISSUE TITLE
After 6.0.1 Upgrade: Notification shade shows on lock screen after waking the screen. 

### ISSUE THREAD

**Issue by eaglz05** [AChep/AcDisplay#132]
The app feels generally a little more buggy since I upgraded. 

I am on Galaxy S6. 
Thanks

**Comment by Kristian60** [comment]
I'm not sure if you are refering to the same issue, but when I receive a notification it is already "greyed-out", as if I already read it. Also, occationally notifications open automatically when i receive them.

Galaxy s7 edge

**Comment by CarlosACepeda** [comment]
Post some screenshots if available please

**Comment by CarlosACepeda** [comment]
Closing as stale, I will reopen the issue if neccesary.
