### ISSUE TITLE
Can't Uninstall after marshmallow update

### ISSUE THREAD

**Issue by arcangel93** [AChep/AcDisplay#135]
Says failed to Uninstall do to unknown error when trying to Uninstall from f-droid

**Comment by Bugsbane** [comment]
Have you disabled it's permissions add the app tells you that you need, to prevent issues with uninstalling? If not, do a quick search and you'll find the instructions easily enough.

**Comment by davidhedlund** [comment]
I can confirm this as well on a Android 4.4.1 (KitKat). Also, I made sure that acDisplay didn't run when I tried to remove it but it still not possible to get rid of it.

**Comment by Bugsbane** [comment]
Once again, did you ensure that the necessary permissions (such as administration  ) were removed first, as the software says you need to before attempting to uninstall?

**Comment by davidhedlund** [comment]
Can you please make a message appear about this when a user try to uninstall it?

**Comment by smichel17** [comment]
Open the app. Click the help button in the title bar and read the first paragraph.

**Comment by davidhedlund** [comment]
Thanks! It would be great if this message turned up when users try to uninstall it. @smichel17

**Comment by CarlosACepeda** [comment]
I guess there's no way to know when a user wants to remove the app.
The only option is to leave that uninstall tip on a dialog.

**Comment by AChep** [comment]
I'm very positive about adding "Having troubles with uninstalling" right to the *freaking FAQ* button. You can not believe how many people are asking this and not reading the FAQ.

**Comment by CarlosACepeda** [comment]
You should update the app only with that as a single option in CAPITAL LETTERS in the menu, so this won't happen anymore.
