### ISSUE TITLE
App doesn't disable default lockscreen

### ISSUE THREAD

**Issue by Bugsbane** [AChep/AcDisplay#137]
I love acdisplay from the look of it, however after I unlock it, I'm taken to my phone's default Samsung lockscreen, meaning I have to unlock twice each time. This is especially annoying given that my main reason for wanting to use acdisplay is because Samsung's lockscreen crashes so much the phone is basically unusable when using a password. I really just wanted to replace it. Because I use encryption though, I'm forced to use a password, and that crashes the lockscreen. I'm hoping there's a way for acdisplay to show as the lockscreen instead...

**Comment by Bugsbane** [comment]
Note this is on a Samsung Galaxy prime running Android 5.1.1

**Comment by AChep** [comment]
You can't use device encryption without stock lockscreen. Android limitations.

**Comment by Bugsbane** [comment]
:( Well, thanks for replying so quickly and letting me know. Displaying a warning and preventing the user from turning on the lockscreen feature when encryption is enabled would go a long way, and save people a lot of time trying to fix the issue. Still, thanks for all your work on a fab FOSS project.
