### ISSUE TITLE
Accelerometer does not work in active mode (Moto E 2015 LTE)

### ISSUE THREAD

**Issue by Remoulade** [AChep/AcDisplay#138]
While using active mode, shaking the phone (Moto E 2015 LTE) does not work.
However the screen turns on, when the proximity/light sensor is uncovered.
Waving in front of the phone works, too.

The accelerometer works fine, I tested it with an app. The default 'active mode' with the 'Moto Info' app does work with the accelerometer, too.

**Comment by AChep** [comment]
'Shake to wake' is enabled when phone is charging (and some other actions https://github.com/AChep/AcDisplay/blob/master/project/app/src/main/java/com/achep/acdisplay/services/activemode/ActiveModeService.java).

**Comment by Remoulade** [comment]
Thanks for your feedback. That was just not obvious from the app itself. :)
