### ISSUE TITLE
Lockscreen Media Widget not working with Sonos Beta 7.2

### ISSUE THREAD

**Issue by islandman59** [AChep/AcDisplay#145]
The widget controls on the lockscreen do nothing for Sonos 7.2.  They worked in the prior version.  The widget works with all other apps, Pandora, Slacker, Google, etc.

**Comment by CarlosACepeda** [comment]
The controls appear and do nothing? or the controls never appear at all?

**Comment by AChep** [comment]
> The controls appear and do nothing? or the controls never appear at all?

Appear and do nothing. This was a bug of a Sonos

**Comment by CarlosACepeda** [comment]
Ye, some music apps don't register a MediaSession...
