### ISSUE TITLE
Galaxy S8 New Aspect Ratio

### ISSUE THREAD

**Issue by BennettSpeaks** [AChep/AcDisplay#147]
The app is not compatible with the new aspect ratio of the galaxy s8 and the s8+ it leaves a stripe on both the top and bottom of the screen unaltered, giving it an odd look.

**Comment by benmeroff** [comment]
Any update on this, or is this not going to be addressed?

**Comment by CarlosACepeda** [comment]
Can you post some screenshots here?

**Comment by benmeroff** [comment]
This looks like it was either solved or isn't an issue anymore for some reason, just opened up AcDisplay again on my OnePlus 6T and I see no bars while unlocking (while the screen shows another fill color it uses all available screen).  Lol replying after 2 years?

**Comment by benmeroff** [comment]
And seeing as the app hasn't been updated since 2015 I'm gonna wager this hasn't been fixed so I'm not really sure what happened to fix this...  It's a shame, this was my favorite AOD implementation before that was even a thing.

**Comment by CarlosACepeda** [comment]
I'm a new collaborator, but, may I close the issue?

**Comment by benmeroff** [comment]
Oh yeah for sure!  Are you picking up development on this project?

**Comment by CarlosACepeda** [comment]
For now, yes.
