### ISSUE TITLE
Cannot remove AcDisplay from device administrators

### ISSUE THREAD

**Issue by nanos** [AChep/AcDisplay#148]
I'm trying to remove AcDisplay from device administrators. 

When doing this I get the mobile frozen for a few seconds, then "Unfortunately, Settings has stopped."

Tried rebooting the phone, but that didn't help. Every other app that I have in my list of Device administrators (I did try them all) works fine, so I assume it has something to do with AcDisplay. Any further thoughts?

**Comment by smichel17** [comment]
This happens to me when I try to remove Android device manager. Go figure.

**Comment by nanos** [comment]
Interesting. That's one of those that is working fine for me ...

**Comment by AChep** [comment]
You can remove device admin rights from AcDisplay/Help dialog. No idea what causes Settings crash, tho.

**Comment by nanos** [comment]
When tapping "disable" in the help dialog there was absolutely no reaction at all. However, device administrator was still disabled. Thanks for that pointer!
