### ISSUE TITLE
android.text.format.Time is deprecated since API 22

### ISSUE THREAD

**Issue by frankFic** [AChep/AcDisplay#149]
Hi,

I noticed that class android.text.format.Time is used at multiple places:
[Line 77 in TimeView.java](https://github.com/AChep/AcDisplay/blob/5d406457b7277c873b0967eb3b7504656d69397b/project/app/src/main/java/com/achep/acdisplay/ui/widgets/TimeView.java#L77)
[Line 29 in InactiveTimeHelper.java](https://github.com/AChep/AcDisplay/blob/5d406457b7277c873b0967eb3b7504656d69397b/project/app/src/main/java/com/achep/acdisplay/InactiveTimeHelper.java#L29)

This API has been deprecated since API level 22 due to multiple problems (may refer to [here](https://developer.android.com/reference/android/text/format/Time.html))

Although it may not cause problems for the time being, I suggest to change it to other alternatives to avoid future bugs.

**Comment by CarlosACepeda** [comment]
Both of them are fixed now. :)
