### ISSUE TITLE
Cannot Uninstall

### ISSUE THREAD

**Issue by gpegg** [AChep/AcDisplay#150]
I have tried to uninstall this app from my Samsung Galaxy s7 many times, but to no avail. When I tried to uninstall it, it said I was unable to uninstall apps that were given administrative rights. I went into the settings app and tried to remove the admin rights from the app, but the settings app freezes and crashes when attempting to remove admin rights. I can remove admin rights from other apps, but not this one. Also, you should update your email on the Google Play Store.

**Comment by smichel17** [comment]
If memory serves, someone else found a workaround in #148

**Comment by gpegg** [comment]
That helped and the app is now uninstalled​. Thank you very much.
