### ISSUE TITLE
Inclusion to F-Droid? 

### ISSUE THREAD

**Issue by Perflyst** [AChep/AcDisplay#154]
F-Droid is a catalogue of free and open source software and is mainly aimed at people who value their privacy and don't want to rely on proprietary services and apps like google, amazon, etc. Status is an awesome app and would definitely fit in the repository. Inclusion policy requires consent of the developer. If you support the idea, I'll fill the inclusion form.

Contributing guide: https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

More information about updates is here:
https://f-droid.org/en/docs/Build_Metadata_Reference/#Update-Check-Mode
https://f-droid.org/en/docs/FAQ_-_App_Developers/#do-i-need-to-tell-you-when-i-update

**Comment by AChep** [comment]
Try searching through their archived apps. It is there
