### ISSUE TITLE
Block phone setting

### ISSUE THREAD

**Issue by lvalladares** [AChep/AcDisplay#22]
In the setting of the phone you can set a "timeout" for the phone to block, 5 minutes or so of inactivity block your phone, less of the configured doesnt block it.

The problem with AcDisplay is directly related with google policy, when a device administrator turn the screen of, the only way to do it its blocking your phone, so, everytime AcDisplay put your screen off by any mean the phone gets blocked.

I've readed that a workaround for this issue its that everytime AcDisplay turn your screen off, it also delete the password/PIN/pattern, and add it again after passed the configured time.

**Comment by Lemming0815** [comment]
it's a security flaw nevertheless.
There must be a more elegant solution...

**Comment by CarlosACepeda** [comment]
Android API does not allow to remove the Keyguard when the lock option is different than 'Swipe'
(i.e. Pattern, PIN, etc.)
