### ISSUE TITLE
Auto display of notification after a wake up

### ISSUE THREAD

**Issue by moneytoo** [AChep/AcDisplay#27]
I put my phone in a desktop stand so it's comfortable for me to view notifications even without touching the phone. Android auto-expands the first notification so I would like something similar from AcDisplay - to auto open either the first one or (better) the latest incoming notification. (As I use "Wake up on notification"). 
I already tried calling method which gets and shows the latest widget from AcDisplayFragment.updateNotificationList() and updateNotificationList.onStart() (and it works). It doesn't seem to be impossible to do though proper solution would probably require use of some queue etc.
I would really like to see an option in AcDisplay allowing such auto preview of notification without any user action.

**Comment by berot3** [comment]
This is a really essential feature. Making the screen wake up on new notifications makes only half sense if I can not read the new notification. Just seeing the new icon is not enough.
Except from this and breathing notifications I think acdisplay will be THE must have app. Thank you.

**Comment by AChep** [comment]
No worries, it's planned ;)
