### ISSUE TITLE
Option to disable acdisplay when running out of battery

### ISSUE THREAD

**Issue by mapreri** [AChep/AcDisplay#28]
Per title.
I'd like both an option to disable the active mode and one to disable all acdisplay.

Thanks for developing acdisplay.

**Comment by afollestad** [comment]
It shouldn't really affect battery too much, especially when you have an AMOLED display. It will actually save battery with an AMOLED display, since black pixels are off and use no energy (if you don't show a wallpaper that is).

**Comment by AChep** [comment]
Here it goes https://github.com/AChep/AcDisplay/commit/20577ca291069ab38c3d0482d16922559ed1f87c
