### ISSUE TITLE
Daydream service

### ISSUE THREAD

**Issue by seanrand** [AChep/AcDisplay#29]
I currently use AcDisplay as lockscreen replacement and figured it would be nice if AcDisplay provided an option to disable the automatic inactivity sleep timer when the phone is docked or charging. That way it could be used as a simple, nice desk clock.

Alternatively (or additionally), I suppose AcDisplay could also implement the Daydream API to provide desk clock functionality without much coding overhead.

**Comment by AChep** [comment]
Yes, definitely the Daydream should be implemented.
