### ISSUE TITLE
Capitalization with the German language

### ISSUE THREAD

**Issue by ulfklose** [AChep/AcDisplay#30]
The translated string reads (this is (almost) correct)

Aktiv Modus, Sperrbildschirm

The app displays (which is not correct):

Aktiv modus, sperrbildschirm

Please see this screenshot:

![screenshot_2014-11-06-23-51-12](https://cloud.githubusercontent.com/assets/47573/4945487/4bbe89b8-6608-11e4-866f-e573883f7caa.png)

**Comment by AChep** [comment]
See the translations on crowdin https://crowdin.com/project/acdisplay
