### ISSUE TITLE
Lockscreen stock bypassing AcDisplay

### ISSUE THREAD

**Issue by KuraudoXS** [AChep/AcDisplay#31]
Hi guys, great app! I hope you resolve this bug.

If I tap home button (physical button) twice, the stock lockscreen appears, can you fix it?

PS: Another thing that i've realized. Sometimes when I wake up the phone, lockscreen stock appears directly bypassing AcDisplay (I think when the phone goes in deep mode).

(from galaxy s4, 4.4.2)

**Comment by afollestad** [comment]
You need to turn the stock lock screen off by switching Security > Screen Lock to "None". There's no way for an app to do that for obvious security reasons.

**Comment by entonjackson** [comment]
I use CM profiles. And for each profile there is a different lockscreen setting. For example: Outside setting has PIN security, whereas Home setting has no security.
Could it be possible in any way to:
1. add PIN security to AcDisplay
2. make usage of the security settings in AcDisplay?

**Comment by KuraudoXS** [comment]
Thanks afollestad, problem solved.

**Comment by CarlosACepeda** [comment]
Closing, already solved.
