### ISSUE TITLE
Lollipop notification mode should be respected

### ISSUE THREAD

**Issue by afollestad** [AChep/AcDisplay#37]
E.g. if the notification mode is "priority", the screen should stay off rather than waking up briefly when a notification is received. Obviously the "None" mode would have to go into that too.

**Comment by AChep** [comment]
Implemented with https://github.com/AChep/AcDisplay/commit/52dc74d978d1edbc55e0a1a70bbd6e601dff5dd8

**Comment by afollestad** [comment]
Thank you, definitely gonna donate soon
