### ISSUE TITLE
Lockscreen is blank when music is playing on Lollipop

### ISSUE THREAD

**Issue by afollestad** [AChep/AcDisplay#38]
This appears to be an issue with a lockscreen widget not working properly:

![screenshot_2015-01-16-17-47-37](https://cloud.githubusercontent.com/assets/1820165/5786267/dbb30f5e-9da7-11e4-9b1b-d39bab1359f2.png)

**Comment by AChep** [comment]
Does it happen with version 3.0.2?

**Comment by afollestad** [comment]
Yeah, it happens with the latest version

**Comment by afollestad** [comment]
Still happens with 3.0.4 too

**Comment by Falx** [comment]
I can confirm that it happens on 3.0.4. too. Had it happen in 3.0.2 while connected to usb charging in my car.

**Comment by Guru24** [comment]
This is still seen in 3.05 :(

**Comment by AChep** [comment]
Should be fine now. https://github.com/AChep/AcDisplay/commit/c57526c8f88fe65a180c8c91e18d300db7af5a26

**Comment by afollestad** [comment]
I can confirm that it's fixed, thanks for your awesome work
