### ISSUE TITLE
Force text and icons to be white with the black background mode

### ISSUE THREAD

**Issue by afollestad** [AChep/AcDisplay#42]
Notifications should be forced to use white text, and white icons (`setColorFilter(Color.WHITE, PorterDuff.Mode.MULTIPLY)` on an `ImageView` or `Paint` instance). They should already be white on API 11 and above, but apps like Inbox have faded-looking icons.

**Comment by AChep** [comment]
What icons & text? Action items?

**Comment by afollestad** [comment]
This screenshot might help illustrate what I mean.

![rsz_screenshot_2015-01-19-14-08-20](https://cloud.githubusercontent.com/assets/1820165/5807067/0918882c-9fe5-11e4-9032-f9339f4e8c05.png)

The expandable actions ("Done" and "Reply All") have text and icons that are a shade of gray, rather than white. The icon for the app itself at the bottom is also a faded gray color. Other apps however have only white used there, and using white is the correct way to do it based on the design guidelines.

It would just help with consistency if you enforced them to be white :)

**Comment by AChep** [comment]
https://github.com/AChep/AcDisplay/commit/f518137dc03ca02ee0f492e54477a569daaf6be3
