### ISSUE TITLE
wrong toast messages when enabling / disabling acdisplay

### ISSUE THREAD

**Issue by eurochild-dps** [AChep/AcDisplay#44]
when using tasker to enable/disable acdisplay via the provided intents the toast messages are reversed.
When is enabled the toast message shows "AcDisplay is disabled"
and when is disabled the toast message shows "AcDisplay is enabled"

**Comment by AChep** [comment]
https://github.com/AChep/AcDisplay/commit/ee52a7b7b7e7ea80ba3becec9c68b4933b7b2dfb
