### ISSUE TITLE
Right half of music controls get cut off

### ISSUE THREAD

**Issue by afollestad** [AChep/AcDisplay#46]
Seems to happen when a song is done and it moves onto the next song in the queue. I'm using Lollipop on a Nexus 6.

**Comment by afollestad** [comment]
Thought I might as well add an image to help explain:

![acdisplay](https://cloud.githubusercontent.com/assets/1820165/6221588/1ba76d64-b60b-11e4-8369-81ad100522f4.png)

**Comment by AChep** [comment]
Should be fixed by https://github.com/AChep/AcDisplay/commit/d9180d62e25f794873cd7124b0a4d021ce53532b
