### ISSUE TITLE
White color filter should be added to expandable action icons

### ISSUE THREAD

**Issue by afollestad** [AChep/AcDisplay#47]
This is a notification from an OTA beta testing system in one of my apps. There should be a little download icon next to the "Download" text, but it's a black icon. AcDisplay should add a white color filter to expandable action icons when the black background is enabled in order to make it visible. 

![rsz_screenshot_2015-02-01-23-04-19](https://cloud.githubusercontent.com/assets/1820165/5996086/74729ea0-aa67-11e4-9148-16f4b830b59c.png)

**Comment by AChep** [comment]
Yeah, but forcing white color may break colorful action icons (which are really bad)...

**Comment by afollestad** [comment]
Well, they shouldn't ever be colorful. They're by the design guidelines supposed to be white on Jellybean/KitKat, and black on Lollipop (based on the background color of the notification itself). @AChep

**Comment by afollestad** [comment]
Same with the actual app icons, they should always be white, since the status bar is always a dark color.

**Comment by AChep** [comment]
https://github.com/AChep/AcDisplay/commit/a91a1d3d178bae6a4d4d260ea99d7dcb9fa1462c

**Comment by afollestad** [comment]
Thank you!
