### ISSUE TITLE
Compatibility with Motorolas own active display 

### ISSUE THREAD

**Issue by rodjun** [AChep/AcDisplay#48]
I'm using AcDisplay mostly as a lock screen replacement because I think that the default active screen on Motorola reacts better and probably uses less battery(it's a native app after all). My problem is that when I unlock my phone directly from Motorolas active screen I still see AcDisplay instead of directly unlocking my phone. I believe that the bug relies on the way Motorola "quick unlocks" the screen, it actually opens the unlock screen but with some kind of unlock command that AcDisplay isn't managing correctly  or just can't manage depending on how it's done.

**Comment by afollestad** [comment]
Motorola's is proprietary and is designed to work with their hardware (for battery efficiency). So I'm guessing there's not much that can be done about this.
