### ISSUE TITLE
Samsung S5 Lollpop

### ISSUE THREAD

**Issue by bnussman** [AChep/AcDisplay#50]
Spotify doesn't connect and show audio controls or cover art on the lock screen after I updated to Android 5.0 in my Samsung Galaxy S5

**Comment by AChep** [comment]
What version of AcDisplay? What firmware? Does it work with other players? _IS IT ACDISPLAY V2.X?_

**Comment by bnussman** [comment]
I'm on 2.4.7 of AcDisplay. My "model number" is SM-G900V. My "hardware version" is G900.05. Pandora does not work.

**Comment by afollestad** [comment]
@bnussman 2.4.7 is not for Lollipop. Did you notice the current version in this repository is much higher (3.0+)? It's designed for Lollipop, the Play Store version is not.

**Comment by bnussman** [comment]
OHHH! My bad, I should have seen that! Thanks @afollestad

**Comment by bnussman** [comment]
When I try to turn on the lock screen, I get this, when I try to open "Usage stats" nothing happens! 
![Image of screenshot](https://i.imgur.com/smYzJ46.png)

http://i.imgur.com/smYzJ46.png

**Comment by bnussman** [comment]
Nevermind about that ^ 
I am on 3.0.10 of AcDisplay, and the Music controls are a bit messed up... 

![acdisplay](http://i.imgur.com/Emvx6nB.jpg)

**Comment by AChep** [comment]
Should be fixed by https://github.com/AChep/AcDisplay/commit/d9180d62e25f794873cd7124b0a4d021ce53532b
