### ISSUE TITLE
Make double tap configurable

### ISSUE THREAD

**Issue by anbroid** [AChep/AcDisplay#56]
Double tap locks the screen. In my case this is undesirable. I use double tap in my phone to wake the screen however this is not always reliable, so sometimes need to tap the screen multiple times to wake the phone but if not careful the phone wakes and we accidentally doubletap AcDisplay which locks the phone again. It happens to me feequently so it would be nice to be able to disable the double tap.

Alternatively, allow AcDisplay to operate without being device administrator, meaning it will perform all functions except turning off the screen. Currently AcDisplay refuses to operate if it is not device administrator.

**Comment by AChep** [comment]
Alternatively, allow AcDisplay to operate without being device administrator, meaning it will perform all functions except turning off the screen. Currently AcDisplay refuses to operate if it is not device administrator.

No, cause it will break the custom screen off timer.

**Comment by anbroid** [comment]
Yes, the screen off timer would not work. But as long as there is no screen wakelock held by acdisplay, the android screen timeout will turn off the screen. So it could be desireable for some users (especially non-savvy ones who have trouble uninstalling apps that are device administrator :-) ) and maybe you could use this approach if you also do #55 (option to disable sleep timer). Just a thought!

**Comment by AChep** [comment]
An option to disable double-tap-to-sleep is here https://github.com/AChep/AcDisplay/commit/a4a0d64b8ace5a8d31b65c2b028f5320266554a8

**Comment by anbroid** [comment]
Thanks! Confirmed it works in latest release!
