### ISSUE TITLE
Option to Disable Shake Detection

### ISSUE THREAD

**Issue by cameronkelley28** [AChep/AcDisplay#57]
Following the shake detection changes in the latest update, my phone now wakes constantly while driving on rougher roads (California freeways are awful) with the phone charging. Would it be possible to add an option to disable shake detection entirely?

**Comment by AChep** [comment]
Done by https://github.com/AChep/AcDisplay/commit/7869d66e47d2a8af38cdd8e192c3f6d33a7e3015
