### ISSUE TITLE
Issues with dark unreadable text in notifications

### ISSUE THREAD

**Issue by afollestad** [AChep/AcDisplay#59]
I circled the block of a few lines of text in this screenshot:

![1425699650917](https://cloud.githubusercontent.com/assets/1820165/6539915/b15b5f90-c449-11e4-8633-39903b40412f.jpg)

This example is from Inbox, is also happens in Hangouts (when you receive a message that only contains an image, the "Picture" text is black).

**Comment by AChep** [comment]
Yeah, I can confirm it too. I was trying to fix it some weeks ago by https://github.com/AChep/AcDisplay/commit/a6d8c8b371e7402b48ecb54f8e9bdf1924d7c34c but no luck.  Actually I have no idea how to fix it, except decompiling Inbox and checking their code. :cry:

**Comment by AChep** [comment]
Fixed by https://github.com/AChep/AcDisplay/commit/a56b2a10ba393e7e06ac8fe6d512c413301a74ef
