### ISSUE TITLE
Screen turning on while proximity sensor is covered

### ISSUE THREAD

**Issue by roseyhead** [AChep/AcDisplay#64]
I've got a Note 4 running 4.4.4. Every time I get a notification from Facebook or whatever my screen turns on in my pocket and if I'm walking the phone will unlock itself with my leg and start skipping songs, rearranging my home screen etc. I'd think the app should check the proximity sensor and not turn the screen on if the sensor is covered.

**Comment by AChep** [comment]
App won't turn screen on if the active mode is enabled.

**Comment by roseyhead** [comment]
I've got active mode turned off currently because I tend to hit the power button out of habit when I take my phone out of my pocket. Turning it on should stop my phone from waking itself up in my pocket? I'll switch it on and see how it goes.
