### ISSUE TITLE
Allow for use of the Rewind and Fast Forward buttons.

### ISSUE THREAD

**Issue by Gloober** [AChep/AcDisplay#67]
I use a Chromecast on a regular basis, and when a video is playing, sometimes I want to skip ahead a little without having to unlock my phone to do so. The pause and play buttons work, but not the forward and reverse buttons, would it be possible to add this functionality?

**Comment by AChep** [comment]
Yes, technically it's possible.

**Comment by AChep** [comment]
https://github.com/AChep/AcDisplay/commit/95eb0d1fccde892f41d6d1c836eff6e70a7bd83a Here we go. Long press to show the seek bar.
![device-2015-04-11-144714](https://cloud.githubusercontent.com/assets/990982/7101278/045f1624-e05a-11e4-9c6d-80e7f9823397.png) ![device-2015-04-11-144559](https://cloud.githubusercontent.com/assets/990982/7101279/09053924-e05a-11e4-9dfd-141f313da104.png)
