### ISSUE TITLE
Full screen mode buggy

### ISSUE THREAD

**Issue by mickeydeagle** [AChep/AcDisplay#74]
Full screen mode (which, as I understand it, hides the status bar and navigation buttons) seems to work sporadically. For example, it works fine when a new notification arrives, or if I press the sleep/wake button on my device to bring up the AcDisplay lock screen. But, if I press the sleep/wake button on my device to put it back to sleep, and then press the power button again, the status bar and navigation buttons slide in.

Behavior observed from a Nexus 6 running 5.1

**Comment by SMillerDev** [comment]
This is probably panic mode being activated by repeatedly turning the screen on and off. @AChep can you confirm?

**Comment by AChep** [comment]
Maybe Panic mode and something else causes this. I'm experiencing this issue from time to time on my non-affected by Panic mode CyanogenMod.

**Comment by CarlosACepeda** [comment]
Closing as stale, though, Panic mode indeed causes this behavior, in stock Android it's a behavior that can't be controlled AFAIK.
