### ISSUE TITLE
Heavy Memory Usage on Samsung devices.

### ISSUE THREAD

**Issue by ghost** [AChep/AcDisplay#78]

**Comment by adhishthite** [comment]
Almost 50 MB usage of my RAM. Please fix.

**Comment by AChep** [comment]
That's not heavy.

**Comment by adhishthite** [comment]
Hi !

Sorry for the short description earlier.

I am running Android 5.0 (stock) on my Galaxy S5, and the latest version of AcDisplay.

I have 2 issues:

1. 50-70 MB memory usage. For a minimal lock screen app, this usage is high. Even a heavy app like WhatsApp uses 80 MB. Please look into it 

2. *ALWAYS* crashes when I open Google Play Music to play songs.

**Comment by AChep** [comment]
@adhishthite can you capture a log of the crash? It would be really helpful.

**Comment by CarlosACepeda** [comment]
Investigating if this still happens

**Comment by AChep** [comment]
> Investigating if this still happens

There's no need, 50-70mb is perfectly fine for such an app. Crash -- I don't think it still happens.

**Comment by CarlosACepeda** [comment]
Closing, AcDisplay does not seem to crash when playing music from G Play Music.
