### ISSUE TITLE
Bug with Podcast Addict and Pocket Casts

### ISSUE THREAD

**Issue by Ack0** [AChep/AcDisplay#79]
*Dynamic Notification* is **not** working properly with *Podcast Addict* and *Pocket
Casts*.
The Podcast Art **Image** only appears sometimes.
Look:
http://i304.photobucket.com/albums/nn191/xkvr/AcDisplay/Pocket%20Casts_zpscugcztn2.gif
http://i304.photobucket.com/albums/nn191/xkvr/AcDisplay/Podcast%20Addict3_zpsdrahttd7.gif

The background image should be the podcast art, but AcDisplay is showing the wallpaper.

Moto G XT1069 Android 5.0.2

**Comment by AChep** [comment]
Should be fine since https://github.com/AChep/AcDisplay/commit/e011b06111e098a27925166ee87a47b8aebe1c01
