### ISSUE TITLE
Force close if any audio player is running

### ISSUE THREAD

**Issue by Ack0** [AChep/AcDisplay#82]
With the version 3.4.3, if I have some audio player running and power off the screen or open AcDisplay directly, it force closes.

**Comment by CarlosKhazs** [comment]
It happens to me as well.

**Comment by AChep** [comment]
![image](https://cloud.githubusercontent.com/assets/990982/7435433/56472790-f04c-11e4-8840-7fb46fbf5411.png)
https://github.com/AChep/AcDisplay/commit/7db6dcd8ca945514b789339b50d2cad681dea08f

**Comment by Ack0** [comment]
Haha ;-)

**Comment by CarlosKhazs** [comment]
Great! We know that AChep ;)
