### ISSUE TITLE
Feature Request: Secured lock screen (PIN lock, pattern lock, etc.)

### ISSUE THREAD

**Issue by halcyonera** [AChep/AcDisplay#91]
Google brought a new 2-step lock screen for Lollipop, and sometimes it's annoying because to input PIN or draw a pattern, you have to swipe and pass the first lock screen containing clock widget and notification list. It takes one more gesture and it's not convenient. It wasn't an issue in previous versions.

It will be good if AcDisplay could have a secured lock screen feature which can replace default secured lock screen.

**Comment by AChep** [comment]
Custom secure lockscreen is not possible to create.
