### ISSUE TITLE
Gradle version not supported

### ISSUE THREAD

**Issue by diiiz** [AChep/AcDisplay#96]
I've Gradle v2.2 and Android Studio says that this project uses an unsupported Gradle version. Please upgrade in order to checkout.

**Comment by AChep** [comment]
AcDisplay requires `gradle-2.4-all` and `com.android.tools.build:gradle:1.2.+` tools. What version of Android Studio are you using?

**Comment by diiiz** [comment]
I'm using AS 1.3
