### ISSUE TITLE
Music Media Widget not working for Spotify

### ISSUE THREAD

**Issue by Youonthebass** [AChep/AcDisplay#99]
Hello.

I have a Nexus 5 running on 5.1.1.
 When playing music with the Spotify app I can't 'click' on the media widget.
This used to work fine, but now it seems not to. I can't get any of the buttons to work no matter how much I try. It works fine with Play Music, every button works, but with Spotify it doesn't.
I do not have active mode enabled, I am running in fullscreen mode.

**Comment by DenizUgur** [comment]
Yup, same problem. It was working just fine before spotify updated to latest version. They might changed how to handle media notification

**Comment by hebertpalomino** [comment]
same here. Note 4 running 5.0.1

**Comment by CarlosACepeda** [comment]
Still happening?

**Comment by CarlosACepeda** [comment]
Closed as stale, feel free to comment again if you think the issue is still relevant, however, I checked myself and this does not happen 🤷‍♂
